### ISSUE TITLE
Presentation: Midterms

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#11]
- [x] Presentation
- [x] NN-Demo (Nuns and penguins)
- [x] Art from Data Demo

**Comment by s3inlc** [comment]
Do we plan to be able to do the Art Demo with already a basically working UI or do we plan to do it in IntelliJ?

I think it should be possible to do in the UI, but it mostly depends on Christian, what he thinks.

**Comment by christianfrei** [comment]
If there aren't big problems in the next days the UI should provide the basically functions. Maybe something isn't nice in css or isn't well displayed but the functionality should be there.

**Comment by silvanheller** [comment]
I would prefer to have a UI prototype so we can have a discussion about features at the presentation

**Comment by christianfrei** [comment]
Prototype is working for Art from Data with whole Movies and Shots; only issue at the moment is that shots are just displayed with its ID and not the Thumbnails

**Comment by christianfrei** [comment]
Art from Data is completely working

**Comment by christianfrei** [comment]
Finished.
