### ISSUE TITLE
API - Art from Data

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#13]
Issue for API-Related things.

API Specification
- [x] List available movies
- [x] List available reconstruction modules
- [x] Return reconstructed image (maybe this needs a bit of help from the php-layer?)

Modes:
- [ ] one shot -> one picture
- [ ] multiple shots -> one picture (one movie -> one picture is included in this mode)

API Implementation

**Comment by lucaro** [comment]
note that there is already an interface for the inverse transform (of a single feature): https://github.com/silvanheller/cineast/blob/adampro/src/org/vitrivr/cineast/core/features/exporter/FeatureVisualizer.java
