### ISSUE TITLE
Model-Deployment within .jar

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#14]
13/10 Waiting for License

The Model is to be deployed outside the jar. Either a gradle-task loads it at build-time or its location is specificed in a config-file
Labels are stored  at extraction-time.
- [x] see core.config for adding a neuralnet-config
- [x] Add which Model / Framework
- [ ] Potential Flags (default downloading off)
- [x] Add gradle-task to load nn from web (Not wget :-1: )
- [x] Location of Model

**Comment by silvanheller** [comment]
We need a persistent Download location which is not based on the torrent-protocol.

**Comment by lucaro** [comment]
If you can guarantee that there will be no license issues vitrivr.org can host them.

**Comment by silvanheller** [comment]
Good point. The original VGG 16 [model](http://www.robots.ox.ac.uk/~vgg/research/very_deep/) is released under the [ Creative Commons Attribution License](https://creativecommons.org/licenses/by/4.0/) which means we must credit the authors but are free to share in any way.

The Code which converts the Caffe model to Tensorflow can be found [here](https://github.com/ry/tensorflow-vgg16) and does unfortunately not have a license. I've opened a [issue](https://github.com/ry/tensorflow-vgg16/issues/8) and hopefully the creator adds a license since his other converter-repo has the MIT License.

**Comment by silvanheller** [comment]
Moving to Final Presentations since we are waiting for the license

**Comment by silvanheller** [comment]
Removed from Final Presentations, it does not look like we are going to get an answer
