### ISSUE TITLE
Art UI Graphs

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#17]
Search which D3.js graphs/types can be used to show Data Art. It is required that there is some way to generate the graph with JSON input, which is not possible on all of the examples here: [https://github.com/d3/d3/wiki/Gallery](https://github.com/d3/d3/wiki/Gallery)

**Comment by s3inlc** [comment]
[http://bl.ocks.org/mbostock/4063423](http://bl.ocks.org/mbostock/4063423)
[http://bl.ocks.org/mbostock/3886394](http://bl.ocks.org/mbostock/3886394) this one would need some small changes to parse JSON instead of csv

**Comment by christianfrei** [comment]
http://bl.ocks.org/mbostock/4063423
http://bl.ocks.org/mbostock/4060954
http://bl.ocks.org/mbostock/4062045
http://bl.ocks.org/mbostock/849853

These 4 d3 graphs are implemented as prototype with testdata in the Art from Data UI at the moment. Can be viewed and tested with the extra button d3Test.

**Comment by silvanheller** [comment]
Needs implementation on the server-side. We will implement 1-2 features for demo purposes

**Comment by silvanheller** [comment]
Implemented
