### ISSUE TITLE
Average Color over whole Videos

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#21]
I did two Visualizations of videos 10 & 11 (IDs from ADAMpro prebuilt) with the VisualizationAverageColorGrid8 which basically means the average color of all the shots on a 8x8 grid.

The results seem to be quite "boring" with the colors, basically it's one color which is a bit more dominant and all the other parts are similar to it.

My question is now, do you think such Visualizations are still useful (as you see the dominant color) or is this "too bad" to be kept implemented?

https://cloud.githubusercontent.com/assets/1167295/18097406/fc92dd18-6edd-11e6-864c-1be777d2ef2f.png
https://cloud.githubusercontent.com/assets/1167295/18097407/fc944e14-6edd-11e6-8f22-c83d43993113.png

**Comment by s3inlc** [comment]
I cannot include the images here as there are problems when github/browser are automatically resizing the images which destroys the original image. Just click on the links, save them and then open it with some program and zoom in.
The images are only 8x8 pixels big!

**Comment by s3inlc** [comment]
I added the possibility to resize image Visualizations, here the same images in a better viewable format:

![movie10](https://cloud.githubusercontent.com/assets/1167295/18099454/e4880e88-6ee6-11e6-90b3-2ac29131a660.png)
![movie11](https://cloud.githubusercontent.com/assets/1167295/18099498/1109c4ba-6ee7-11e6-9075-3f58a8e6e1fa.png)

**Comment by silvanheller** [comment]
I think this is quite interesting for short videos. Just scrolling through the thumbnails, i was able to easily guess which picture belonged to which movie.
It's obviously not going to be very relevant for full length films, but since our collection is for short videos, i suggest we leave it in as a very basic example. 
Maybe it would be more interesting to take the  average for every 5-10 shots and then concat those images to represent the whole movie.

**Comment by s3inlc** [comment]
Thanks for the feedback.
Am I understanding correctly that you mean by 'concat' that the images for the 5-10 shots are put side by side (vertically for example)?

**Comment by lucaro** [comment]
You could also do this for every shot and arrange the outputs into one large image, either by arranging them horizontally (or vertically) or by putting them into a rectangular arrangement. The UI could then simply display the relevant part of the image. Scaling could also be done by the UI so there is no need to use more than one pixel per segment.

**Comment by silvanheller** [comment]
@lucaro  See Drafts in #22

**Comment by s3inlc** [comment]
I think @lucaro meant something other than the stripe. Like he wrote, grid8 frames arranged in a rectangular form for the whole movie. I added these modules now, below an example of the move 11 with mediancolorgrid8:

![image](https://cloud.githubusercontent.com/assets/1167295/18231130/3f9ffc00-72b0-11e6-8410-86f5c5955359.png)

**Comment by lucaro** [comment]
Yes, exactly.
