### ISSUE TITLE
Concatenated AverageColor from shots

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#22]
As suggested by Silvan, here the stripes of the average color of the shots again of movie ID 10 & 11.
It might be interesting if there is a way to make the changes of the colors smoother and how this will look.

![movie10_stripe](https://cloud.githubusercontent.com/assets/1167295/18104334/00c7b9d6-6efb-11e6-95ab-13c01ec3a212.png)
![movie11_stripe](https://cloud.githubusercontent.com/assets/1167295/18104335/00cda580-6efb-11e6-90e0-86ad338158f6.png)

**Comment by lucaro** [comment]
Smoothing can most easily be achieved by generating the images with one pixel slices per shot and then scaling them (using an linear interpolation function) up by a multiple of 2. I would be interested to see the difference between the average- and the median shot color. I would expect the median colors to be slightly more vibrant.

**Comment by s3inlc** [comment]
Movie 11 here now with comparison of median and average color:

AverageColor:
![imageaveragecolorstripe 11](https://cloud.githubusercontent.com/assets/1167295/18123493/6b9f5f8e-6f6e-11e6-85db-29e7d7cfde5c.png)
MedianColor:
![imagemediancolorstripe 11](https://cloud.githubusercontent.com/assets/1167295/18123492/6b9f3252-6f6e-11e6-8d32-4404d8aa247c.png)

**Comment by lucaro** [comment]
yes, that looks about as expected...

**Comment by s3inlc** [comment]
This is a very good idea to make the width dependent from the length of the shot, will try this out.

**Comment by s3inlc** [comment]
With variable width of the shots you can really see big differences in shot length (movie 11 here with AverageColor and MedianColor):

![image](https://cloud.githubusercontent.com/assets/1167295/18205481/7793fe2a-7122-11e6-9292-10d7d3020d0b.png)

![image](https://cloud.githubusercontent.com/assets/1167295/18205474/7071610a-7122-11e6-8bbd-6d6f65205524.png)
