### ISSUE TITLE
Entry-level concepts

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#23]
See commit 2143a670dc1270c7d1767af4129e4b9144d88765 for suggestions. If you look at https://github.com/silvanheller/cineast/blob/adampro/src/resources/classes.csv
Some entry-level concepts take up a lot of space. Maybe we should exclude some of them.

bird, machine, adult, vehicle, animal, plant, food, fish, flower, tool, tree, object, dog, bush, Tree(big/small???), Fish (big/small???), flower with stem..., vessel, Bush(b/s???), vegetable, fruit, person, grass, furniture, standing bird, cloth, building

**Comment by s3inlc** [comment]
What exactly is the problem with these large types?
Is it because the value of the table would become that big?

**Comment by silvanheller** [comment]
Needs Testing when we performed extraction #5

**Comment by silvanheller** [comment]
We just eliminate duplicates and really unnecessary classes. Everything else is premature optimization, especially given that there is now code for SELECT * from ... IN (...)
