### ISSUE TITLE
ShotLookup/VideoLookup Integration into API

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#27]
https://github.com/silvanheller/cineast/commit/03fa3a8ae2177205aabec084f5595a9e068da485
https://github.com/silvanheller/cineast/commit/21721bef18bc494d5cc89a25e8b6966c7f548202

Following the comments here, the listshots / listvideos functionality should use the shotlookup resp. videolookup-class.

**Comment by s3inlc** [comment]
ShotLookup is now used for getting the shots of a movie in the API call in commit https://github.com/silvanheller/cineast/commit/343359b1b16eb40b30aad117d032edbfc579a55a

**Comment by lucaro** [comment]
The reworked logic is now available. In the next version of the pre-built docker container we will also provide the sequence numbers.
