### ISSUE TITLE
DominantEdges combined with AverageColor

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#28]
I combined the DominantEdgeGrid8 feature with the AverageColorGrid8 feature. So if in the grid there is a dominant edge present, it will draw a gradient in the direction of the edge between the average color and white, otherwise it just draws the average color.

This is an example with shot 65563:
![image](https://cloud.githubusercontent.com/assets/1167295/18204137/5e2e7afc-711b-11e6-8492-83b4fdc7496d.png)

Which results in following output:
![image](https://cloud.githubusercontent.com/assets/1167295/18204150/7442df40-711b-11e6-9055-70dd20145488.png)

Any opinions about this result, is it something worthy to include or should it be represented in another way?

**Comment by s3inlc** [comment]
Two other examples:

segment 1900546:
![image](https://cloud.githubusercontent.com/assets/1167295/18204455/2cee6388-711d-11e6-90e6-0498e17c756b.png)
![image](https://cloud.githubusercontent.com/assets/1167295/18204445/221cd96c-711d-11e6-8b97-5d38c8c5bc91.png)

segment 720900:
![image](https://cloud.githubusercontent.com/assets/1167295/18204518/829ce4f8-711d-11e6-8272-20ada29ef687.png)
![image](https://cloud.githubusercontent.com/assets/1167295/18204523/8d0eccf8-711d-11e6-96f5-e20211cee9d1.png)

**Comment by s3inlc** [comment]
I'm still waiting for some feedback on this ;)

**Comment by lucaro** [comment]
For what it's worth, I think it is interesting.

**Comment by silvanheller** [comment]
I think it's interesting too. I'm still not happy with how we represent the edges but i can't come up with a better solution atm
