### ISSUE TITLE
Shot List Sorting

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#30]
ADAMpro is not returning the segments of a requested multimediaobject ordered by id. So most of the visualization modules are not handling this correctly.
This requires to update all the modules which will probably result in quite other images as the ones which were provided.

**Comment by s3inlc** [comment]
Here you can see the difference (movie 11):

![image](https://cloud.githubusercontent.com/assets/1167295/18231007/561cf9aa-72ac-11e6-8c85-f8a93847db2a.png)
![image](https://cloud.githubusercontent.com/assets/1167295/18231008/5b9fa3dc-72ac-11e6-9ee9-e38f517e280c.png)

**Comment by silvanheller** [comment]
Yeah, the one on the bottom looks way more realistic. Nice catch noticing the id-thing :+1:

**Comment by s3inlc** [comment]
I implemented a sort function for sorting a list of objects in the ArtUtil class.
I noticed it because I was implementing the grid8square visualization where I noticed that the frames were not in order but mixed over the whole image.
