### ISSUE TITLE
ShotDescriptor has no sequence number value

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#31]
ShotDescriptor only provides frame numbers and the IDs of the shot and video, but not the 'number' of the shot inside the multimediaobject which I need to sort the list I get from the ShotLookup.

**Comment by s3inlc** [comment]
As soon as the new ShotLookup classes are available this should be updated in the ArtUtil.sortBySequenceNumber() function. Until then, it's done by sorting with segmentId

**Comment by s3inlc** [comment]
see commit https://github.com/silvanheller/cineast/commit/7254c51d850bdd3d7332ad2316746cbda5c8617b
sorting is now done with the SegmentDescriptorComparator, there the update needs to be done after merging.

**Comment by silvanheller** [comment]
With fcb450127c790d31cd7749f16137a86ebf47b352 we merged the new Lookups from the main repo. SegmentDescriptorComparator is correct, the getShotId() method just returns the segmentID.

**Comment by s3inlc** [comment]
Why is segmentId a String, I thought it should a number as then it's clear that it is a number @lucaro ?

**Comment by s3inlc** [comment]
the comparator is now updated in https://github.com/silvanheller/cineast/commit/444d1c7bfb238dde7afa53818599ea00c134e613
