### ISSUE TITLE
Color rotated in Art from Data results

### ISSUE THREAD

**Issue by christianfrei** [silvanheller/cineast#39]
The color of the result image is rotated either clockwise or anti-clockwise (see pictures below). It is only in the features with color, edges are not affected.

![721057](https://cloud.githubusercontent.com/assets/21161156/18492467/ca9b020c-7a0b-11e6-917c-e71d578e5bce.jpg)
![index](https://cloud.githubusercontent.com/assets/21161156/18492471/ce908e18-7a0b-11e6-99ab-09ec377cfcd5.png)

![721073](https://cloud.githubusercontent.com/assets/21161156/18492498/eb2cbd6c-7a0b-11e6-9de6-075b15d9e2a2.jpg)
![index2](https://cloud.githubusercontent.com/assets/21161156/18492505/ef1a04ca-7a0b-11e6-929f-19c7c6816dc7.png)

**Comment by s3inlc** [comment]
fixed with the latest commit
