### ISSUE TITLE
Storing precomputed Movie Visualizations

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#41]
It would be ideal if there was a way to store the precomputed Visualizations. 
This needs both work on the visualization modules and integration into the DB-Side

**Comment by lucaro** [comment]
Don't store images in the database, that's not what they are for. Have a caching layer in your run time which checks a (file system) cache before executing a module and stores its output after calling it. This way, the modules don't need to know anything about the caching.

**Comment by s3inlc** [comment]
Basic caching is now implemented. The images get saved as base64 encoded text file to make it easier to also support the caching of the JSON data for graphs which will be used in some Visualization Modules.
