### ISSUE TITLE
Adjust size of result images of some Visualization Modules

### ISSUE THREAD

**Issue by s3inlc** [silvanheller/cineast#43]
Because the resizing in browsers always results in a loss of the exact pixels, some Modules (e.g. AverageColorGrid8 or AverageColorGrid8Square) need to create an image with a big enough size. 
Otherwise the quality when viewing in browsers will be bad.

**Comment by lucaro** [comment]
Not true: https://builtvisible.com/image-scaling-in-css/

**Comment by silvanheller** [comment]
'Finally, whilst Internet Explorer does not support image-rendering, we can achieve the same effect by using a non-standard property that has been knocking around since IE 7.'

Classic Internet Explorer

**Comment by s3inlc** [comment]
Ok, in this case this is a task for @christianfrei to set this for all images on the vitrivr-ui.

**Comment by s3inlc** [comment]
For the visualizations which are stripes, the height is now reduced to one pixel

**Comment by christianfrei** [comment]
implemented feature thanks to @lucaro 

Long stripes have to be cutted or resized in width, but I will close this issue here and open for this a new one in the UI repo.
