### ISSUE TITLE
Support for Multiple Shots: Art from Data

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#46]
The API should support an array of shots as input and return visualizations for all of them.

The UI needs currently just to adjust its queries. UI rework needs to be discussed.

**Comment by christianfrei** [comment]
UI supports multiple shots for one selected movie by clicking on the wished thumbnails and adding it to an array. At the moment just the first element of an array will be send by query, will be changed as soon as the back-end supports the array.

**Comment by christianfrei** [comment]
Implemented different cases for "shots" and "multiple-shots". I named the type for multiple shots "VISUALIZATION_MULTIPLESEGMENTS", the one for single shots remained at "VISUALIZATION_SEGMENT"

**Comment by christianfrei** [comment]
works
