### ISSUE TITLE
DB Integration

### ISSUE THREAD

**Issue by silvanheller** [silvanheller/cineast#6]
Table 1: shotid | objectid | certainty
Table 2: objectid | label
Table 3: shotid | classification vector full 1k matches

- [x] Where do we create tables?
- [x] What is the preferred way of checking if a table exists?
- [x] Test existsEntity()-Code
- [ ] Creating indices on columns (specifically, the label in table 1)
- [x] Does a featuretable automatically create an index? -> no, See EntityCreator
- [x] Maybe perform refactoring and store same concepts as two different strings with same ID?

**Comment by lucaro** [comment]
see: https://github.com/silvanheller/cineast/blob/adampro/src/org/vitrivr/cineast/core/setup/Setup.java

**Comment by silvanheller** [comment]
Needs code review & maybe refactoring of index-creation code

**Comment by silvanheller** [comment]
Our Featuremodule is on the same level as the other feature modules when it comes to indexfunctionality

**Comment by silvanheller** [comment]
Closing as there need to be internal discussion about how we handle indices
